FROM python:3.11-slim

RUN apt-get update && apt-get install -y git curl wget && \
    pip install --upgrade pip

WORKDIR /app

COPY ironshell/requirements.txt .
RUN pip install -r requirements.txt

COPY . /app

# Установи нужные CLI-сканеры, пример:
RUN pip install bandit checkov
RUN wget -O /usr/local/bin/gitleaks https://github.com/gitleaks/gitleaks/releases/download/v8.18.2/gitleaks_8.18.2_linux_x64 \
    && chmod +x /usr/local/bin/gitleaks

# ...повтори для других CLI

CMD ["python", "main.py", "--help"]